.TH tempread 8
.SH NAME
tempread \- read temprature and monitor its changes
.SH SYNOPSIS
.B tempread
[\fB\-d\fR]
[\fIdevice ID\fR]
.SH DESCRIPTION
.B tempread
read current temperature of selected sensor
.SH OPTIONS
.TP
.BR \-d     
\fIserial number\fR
.TP
set default device ID 
.TP
.BR \-v
verbose mode
.TP
.BR non
display the raw sensor output
